### ISSUE TITLE
PWP Capstone Feedback

### ISSUE THREAD

**Issue by mackenzieyoung** [miikkij/tomerater#1]
## Rubric Score
 
### Criteria 1: Valid Python Code
* _Score Level:_ 4 (Exceeds expectations)
* _Comment(s):_ Great job, your code runs without any errors.
 
### Criteria 2: Implementation of Project Requirements
* _Score Level:_ 4 (Exceeds expectations)
* _Comment(s):_ Very good, your code produces the suite of functions and classes required of it and calls them in an appropriate order. Nice job going above and beyond by including extra functions like `get_worth_of_user`, and you did a good job testing all of your functions as well.
 
### Criteria 3: Software Architecture
* _Score Level:_ 4 (Exceeds expectations)
* _Comment(s):_ Good, your code is separated into distinct classes and functions, each of which are invoked for their own purposes.
 
### Criteria 4: Uses Python Language Features
* _Score Level:_ 4 (Exceeds expectations)
* _Comment(s):_ Nice job, your code uses Python features appropriately. One small change I would make would be to add a `__repr__` method to the Book class.
 
### Overall Score: 16/16
Excellent work!

**Comment by miikkij** [comment]
Thank you for the feedback. I had a feeling that I missed something, good catch!

I've added the `__repr__` method for the Book class. Now it feels complete. Thanks again.
